"""baseline: bestehendes Schema (Stand vor Phase 13)

Revision ID: 0001
Revises: 
Create Date: 2026-08-17 08:36:07.739619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_project_catalog',
    sa.Column('jira_project_key', sa.String(length=50), nullable=False),
    sa.Column('relevant', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('jira_project_key')
    )
    op.create_table('jira_worklogs_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_account_id', sa.String(length=100), nullable=False),
    sa.Column('jira_issue_key', sa.String(length=50), nullable=False),
    sa.Column('datum', sa.String(length=10), nullable=False),
    sa.Column('stunden', sa.Float(), nullable=False),
    sa.Column('projekt_mapping', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_account_id', 'jira_issue_key', 'datum', name='uq_worklog_eintrag')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kunde', sa.String(length=200), nullable=True),
    sa.Column('start_monat', sa.String(length=7), nullable=False),
    sa.Column('anzahl_monate', sa.Integer(), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('jira_component', sa.String(length=200), nullable=True),
    sa.Column('jira_project_key', sa.String(length=50), nullable=True),
    sa.Column('projektleiter', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_project_key')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unassigned_jira_authors',
    sa.Column('jira_account_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('jira_account_id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entschieden_von', sa.String(length=200), nullable=True),
    sa.Column('entschieden_am', sa.String(length=10), nullable=True),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dateiname', sa.String(length=300), nullable=False),
    sa.Column('speicherpfad', sa.String(length=500), nullable=False),
    sa.Column('mimetype', sa.String(length=120), nullable=True),
    sa.Column('groesse_bytes', sa.Integer(), nullable=False),
    sa.Column('hochgeladen_von', sa.String(length=200), nullable=True),
    sa.Column('hochgeladen_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gap_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('monat', sa.String(length=10), nullable=False),
    sa.Column('soll', sa.Float(), nullable=False),
    sa.Column('ist', sa.Float(), nullable=True),
    sa.Column('gap', sa.Float(), nullable=True),
    sa.Column('hochrechnung', sa.Float(), nullable=True),
    sa.Column('erstellt_am', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_minutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('datum', sa.String(length=10), nullable=False),
    sa.Column('teilnehmer', sa.String(length=500), nullable=True),
    sa.Column('text', sa.String(length=5000), nullable=False),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_fte_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('monat', sa.String(length=10), nullable=False),
    sa.Column('wert_soll', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'monat')
    )
    op.create_table('project_gantt_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('monat', sa.String(length=10), nullable=False),
    sa.Column('phase_code', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'monat', 'phase_code')
    )
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.String(length=2000), nullable=True),
    sa.Column('wahrscheinlichkeit', sa.String(length=10), nullable=False),
    sa.Column('auswirkung', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('faellig_am', sa.String(length=10), nullable=True),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subprojects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'entity_type', 'entity_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('zustaendig', sa.String(length=200), nullable=True),
    sa.Column('faellig_am', sa.String(length=10), nullable=True),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('jira_account_id', sa.String(length=100), nullable=True),
    sa.Column('wochenstunden', sa.Float(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('fte', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=True),
    sa.Column('monat', sa.String(length=10), nullable=True),
    sa.Column('phase_code', sa.String(length=1), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'entity_type', 'entity_id')
    )
    op.create_table('fte_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=False),
    sa.Column('monat', sa.String(length=10), nullable=False),
    sa.Column('wert_soll', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subproject_id', 'monat')
    )
    op.create_table('gantt_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=False),
    sa.Column('monat', sa.String(length=10), nullable=False),
    sa.Column('phase_code', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subproject_id', 'monat', 'phase_code')
    )
    op.create_table('plan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=True),
    sa.Column('bereich', sa.String(length=20), nullable=False),
    sa.Column('monat', sa.String(length=10), nullable=True),
    sa.Column('feld', sa.String(length=50), nullable=False),
    sa.Column('alter_wert', sa.String(length=500), nullable=True),
    sa.Column('neuer_wert', sa.String(length=500), nullable=True),
    sa.Column('geaendert_am', sa.String(length=40), nullable=False),
    sa.Column('kommentar_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['kommentar_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_history')
    op.drop_table('gantt_phases')
    op.drop_table('fte_plan')
    op.drop_table('document_links')
    op.drop_table('comments')
    op.drop_table('assignments')
    op.drop_table('team_members')
    op.drop_table('tasks')
    op.drop_table('tag_links')
    op.drop_table('subprojects')
    op.drop_table('risks')
    op.drop_table('project_gantt_phases')
    op.drop_table('project_fte_plan')
    op.drop_table('meeting_minutes')
    op.drop_table('gap_snapshots')
    op.drop_table('documents')
    op.drop_table('decisions')
    op.drop_table('unassigned_jira_authors')
    op.drop_table('teams')
    op.drop_table('tags')
    op.drop_table('projects')
    op.drop_table('jira_worklogs_cache')
    op.drop_table('jira_project_catalog')
    # ### end Alembic commands ###
