"""Konsolidierte Baseline (Squash der Historie 0001-0014).

Revision ID: 0001_consolidated
Revises:
Create Date: 2026-08-17 23:18:23.085846

Warum Squash (siehe CONCEPT.md Abschnitt 12.1, Migrations-Policy):
Die Kette 0001-0014 enthielt zwei Revisionen, die denselben Schiefstand des
Phase-26.9-Cutover-Versuchs abbilden: 0013 (destruktiv: droppt Gantt/FTE-Grid,
TeamMember/Assignment, projects.projektleiter) und 0014 (stellt die Tabellen
strukturell leer wieder her). Auf frischen DBs ergab das ein No-Op-Drop-and-
Recreate-Paar, auf DBs mit Bestandsdaten einen irreversiblen Datenverlust.
Alle bekannten Datenbanken sind leer/pre-production - daher wurde die Historie
per Nutzerentscheidung zu genau dieser einen Baseline verdichtet.

Diese Baseline bildet exakt das Schema ab, das die alte Kette an ihrem Head
(0014) erzeugt hat (per Alembic-Check gegen die Dev-DB verifiziert):
  - alle 49 Tabellen des Zielstandes, inkl. der vorerst beibehaltenen
    Legacy-Planungstabellen (gantt_phases, fte_plan, team_members,
    assignments, ...) - deren fachlicher Cutover (PlanPhase/Milestone führend,
    CONCEPT.md Abschnitt 11 Punkt 26) ist ein separater, zukünftiger Schritt
    mit eigener Datenkonvertierung, keine destruktive Drop-Migration.
  - Seeds: Permissions-Grundvokabular (vormals 0003) und
    Health-Threshold-Defaults (vormals 0010).

DBs, die bereits auf der alten Kette stehen, werden über db_bootstrap.py
berücksichtigt (Retired-Revisionen '0001'..'0014' werden erkannt; Stand
'0014' ist schema-identisch und wird auf diese Baseline gestempelt, ältere
Zwischenstände werden mit klarer Fehlermeldung abgelehnt).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_consolidated'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Grundvokabular aus Master-MD Abschnitt 31 - Seed aus der ehemaligen Migration 0003.
_SEED_PERMISSIONS = [
    "PROJECT_CREATE",
    "PROJECT_EDIT",
    "PLANNING_EDIT",
    "CAPACITY_EDIT",
    "TEAM_MANAGE",
    "PERSON_MANAGE",
    "TAG_MANAGE",
    "TAXONOMY_MANAGE",
    "TASK_MANAGE",
    "DECISION_MANAGE",
    "BLOCKER_MANAGE",
    "ADMIN_ACCESS",
]

# Default-Schwellwerte (yellow, red) - Seed aus der ehemaligen Migration 0010, siehe
# backend/app/health_calc.py DEFAULT_THRESHOLDS (dort als defensiver Fallback gehalten).
_DEFAULT_THRESHOLDS = [
    ("schedule_days", 7, 14),
    ("capacity_fte", 0.2, 0.5),
    ("progress_pp", 10, 20),
    ("risk_score", 3, 5),
    ("blocker_severity", 1, 3),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('capacity_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entity_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_entity_type', sa.String(length=30), nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_type', sa.String(length=30), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('created_by_person_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_type', 'source_entity_id', 'target_entity_type', 'target_entity_id', 'relation_type')
    )
    op.create_table('health_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=30), nullable=False),
    sa.Column('yellow', sa.Float(), nullable=False),
    sa.Column('red', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric')
    )
    op.create_table('jira_project_catalog',
    sa.Column('jira_project_key', sa.String(length=50), nullable=False),
    sa.Column('relevant', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('jira_project_key')
    )
    op.create_table('jira_worklogs_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_account_id', sa.String(length=100), nullable=False),
    sa.Column('jira_issue_key', sa.String(length=50), nullable=False),
    sa.Column('datum', sa.String(length=10), nullable=False),
    sa.Column('stunden', sa.Float(), nullable=False),
    sa.Column('projekt_mapping', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_account_id', 'jira_issue_key', 'datum', name='uq_worklog_eintrag')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('jira_account_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resource_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unassigned_jira_authors',
    sa.Column('jira_account_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('jira_account_id')
    )
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('absence_type', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity_calendar_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['capacity_calendar_id'], ['capacity_calendars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capacity_calendar_id', 'date')
    )
    op.create_table('internal_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('fte', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'skill_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kunde', sa.String(length=200), nullable=True),
    sa.Column('start_monat', sa.String(length=7), nullable=False),
    sa.Column('anzahl_monate', sa.Integer(), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('jira_component', sa.String(length=200), nullable=True),
    sa.Column('jira_project_key', sa.String(length=50), nullable=True),
    sa.Column('projektleiter', sa.String(length=200), nullable=True),
    sa.Column('projektleiter_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projektleiter_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_project_key')
    )
    op.create_table('resource_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('weekly_hours', sa.Float(), nullable=False),
    sa.Column('capacity_relevant', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['app_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ai_relevant', sa.Boolean(), nullable=False),
    sa.Column('ai_description', sa.String(length=1000), nullable=True),
    sa.Column('synonyms', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tag_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('jira_account_id', sa.String(length=100), nullable=True),
    sa.Column('wochenstunden', sa.Float(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('working_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('capacity_calendar_id', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.String(length=10), nullable=False),
    sa.Column('valid_to', sa.String(length=10), nullable=True),
    sa.Column('weekly_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['capacity_calendar_id'], ['capacity_calendars.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('fte', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baseline_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('created_by_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blockers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('active_since', sa.String(length=10), nullable=True),
    sa.Column('caused_by_party', sa.String(length=20), nullable=False),
    sa.Column('waiting_for_party', sa.String(length=20), nullable=False),
    sa.Column('owner_person_id', sa.Integer(), nullable=True),
    sa.Column('owner_team_id', sa.Integer(), nullable=True),
    sa.Column('next_action', sa.String(length=500), nullable=True),
    sa.Column('impact', sa.String(length=500), nullable=True),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['owner_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['owner_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.String(length=2000), nullable=True),
    sa.Column('begruendung', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entschieden_von_person_id', sa.Integer(), nullable=True),
    sa.Column('entschieden_am', sa.String(length=10), nullable=True),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['entschieden_von_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dateiname', sa.String(length=300), nullable=False),
    sa.Column('speicherpfad', sa.String(length=500), nullable=False),
    sa.Column('mimetype', sa.String(length=120), nullable=True),
    sa.Column('groesse_bytes', sa.Integer(), nullable=False),
    sa.Column('hochgeladen_von', sa.String(length=200), nullable=True),
    sa.Column('hochgeladen_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gap_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('monat', sa.String(length=10), nullable=False),
    sa.Column('soll', sa.Float(), nullable=False),
    sa.Column('ist', sa.Float(), nullable=True),
    sa.Column('gap', sa.Float(), nullable=True),
    sa.Column('hochrechnung', sa.Float(), nullable=True),
    sa.Column('erstellt_am', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_minutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('datum', sa.String(length=10), nullable=False),
    sa.Column('teilnehmer', sa.String(length=500), nullable=True),
    sa.Column('text', sa.String(length=5000), nullable=False),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_fte_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('monat', sa.String(length=10), nullable=False),
    sa.Column('wert_soll', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'monat')
    )
    op.create_table('project_gantt_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('monat', sa.String(length=10), nullable=False),
    sa.Column('phase_code', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'monat', 'phase_code')
    )
    op.create_table('project_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('project_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_role_id'], ['project_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'person_id')
    )
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.String(length=2000), nullable=True),
    sa.Column('wahrscheinlichkeit', sa.String(length=10), nullable=False),
    sa.Column('auswirkung', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_person_id', sa.Integer(), nullable=True),
    sa.Column('faellig_am', sa.String(length=10), nullable=True),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['owner_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subprojects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'entity_type', 'entity_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('zustaendig_person_id', sa.Integer(), nullable=True),
    sa.Column('faellig_am', sa.String(length=10), nullable=True),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['zustaendig_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baseline_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['baseline_id'], ['baseline_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=True),
    sa.Column('monat', sa.String(length=10), nullable=True),
    sa.Column('phase_code', sa.String(length=1), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'entity_type', 'entity_id')
    )
    op.create_table('fte_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=False),
    sa.Column('monat', sa.String(length=10), nullable=False),
    sa.Column('wert_soll', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subproject_id', 'monat')
    )
    op.create_table('gantt_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=False),
    sa.Column('monat', sa.String(length=10), nullable=False),
    sa.Column('phase_code', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subproject_id', 'monat', 'phase_code')
    )
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('baseline_date', sa.String(length=10), nullable=True),
    sa.Column('forecast_date', sa.String(length=10), nullable=True),
    sa.Column('actual_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_person_id', sa.Integer(), nullable=True),
    sa.Column('owner_team_id', sa.Integer(), nullable=True),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['owner_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['owner_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=True),
    sa.Column('phase_type', sa.String(length=100), nullable=False),
    sa.Column('baseline_start', sa.String(length=10), nullable=True),
    sa.Column('baseline_end', sa.String(length=10), nullable=True),
    sa.Column('forecast_start', sa.String(length=10), nullable=True),
    sa.Column('forecast_end', sa.String(length=10), nullable=True),
    sa.Column('actual_start', sa.String(length=10), nullable=True),
    sa.Column('actual_end', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('owner_person_id', sa.Integer(), nullable=True),
    sa.Column('owner_team_id', sa.Integer(), nullable=True),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['owner_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['owner_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=True),
    sa.Column('bereich', sa.String(length=20), nullable=False),
    sa.Column('monat', sa.String(length=10), nullable=True),
    sa.Column('feld', sa.String(length=50), nullable=False),
    sa.Column('alter_wert', sa.String(length=500), nullable=True),
    sa.Column('neuer_wert', sa.String(length=500), nullable=True),
    sa.Column('geaendert_am', sa.String(length=40), nullable=False),
    sa.Column('kommentar_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['kommentar_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('plan_phase_id', sa.Integer(), nullable=True),
    sa.Column('resource_role_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('fte', sa.Float(), nullable=False),
    sa.Column('commitment_level', sa.String(length=20), nullable=False),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['plan_phase_id'], ['plan_phases.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resource_role_id'], ['resource_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_demand_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('fte', sa.Float(), nullable=False),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['resource_demand_id'], ['resource_demands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_demand_id', 'person_id')
    )
    # ### end Alembic commands ###

    permissions = sa.table("permissions", sa.column("id", sa.Integer), sa.column("name", sa.String))
    for name in _SEED_PERMISSIONS:
        op.get_bind().execute(sa.insert(permissions).values(name=name))

    health_thresholds = sa.table(
        "health_thresholds",
        sa.column("metric", sa.String),
        sa.column("yellow", sa.Float),
        sa.column("red", sa.Float),
    )
    op.bulk_insert(
        health_thresholds,
        [{"metric": metric, "yellow": yellow, "red": red} for metric, yellow, red in _DEFAULT_THRESHOLDS],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_assignments')
    op.drop_table('resource_demands')
    op.drop_table('plan_history')
    op.drop_table('plan_phases')
    op.drop_table('milestones')
    op.drop_table('gantt_phases')
    op.drop_table('fte_plan')
    op.drop_table('document_links')
    op.drop_table('comments')
    op.drop_table('baseline_entries')
    op.drop_table('tasks')
    op.drop_table('tag_links')
    op.drop_table('subprojects')
    op.drop_table('risks')
    op.drop_table('project_memberships')
    op.drop_table('project_gantt_phases')
    op.drop_table('project_fte_plan')
    op.drop_table('meeting_minutes')
    op.drop_table('gap_snapshots')
    op.drop_table('documents')
    op.drop_table('decisions')
    op.drop_table('blockers')
    op.drop_table('baseline_snapshots')
    op.drop_table('assignments')
    op.drop_table('working_times')
    op.drop_table('team_members')
    op.drop_table('tags')
    op.drop_table('role_permissions')
    op.drop_table('resource_profiles')
    op.drop_table('projects')
    op.drop_table('person_skills')
    op.drop_table('internal_allocations')
    op.drop_table('holidays')
    op.drop_table('absences')
    op.drop_table('unassigned_jira_authors')
    op.drop_table('teams')
    op.drop_table('tag_categories')
    op.drop_table('skills')
    op.drop_table('resource_roles')
    op.drop_table('project_roles')
    op.drop_table('persons')
    op.drop_table('permissions')
    op.drop_table('jira_worklogs_cache')
    op.drop_table('jira_project_catalog')
    op.drop_table('health_thresholds')
    op.drop_table('entity_relations')
    op.drop_table('capacity_calendars')
    op.drop_table('app_roles')
    # ### end Alembic commands ###
