"""phase13: TagCategory und EntityRelation

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-17 08:36:29.057998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_entity_type', sa.String(length=30), nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_type', sa.String(length=30), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('created_by_person_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_type', 'source_entity_id', 'target_entity_type', 'target_entity_id', 'relation_type')
    )
    op.create_table('tag_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # batch_alter_table statt add_column+create_foreign_key direkt: SQLite unterstützt kein
    # ALTER TABLE ... ADD CONSTRAINT, Alembic baut die Tabelle im Batch-Modus per Copy-Move
    # neu auf. Unter Postgres läuft dieselbe Operation als normales ALTER TABLE.
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tags_category_id_tag_categories', 'tag_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tags_category_id_tag_categories', type_='foreignkey')
        batch_op.drop_column('category_id')
    op.drop_table('tag_categories')
    op.drop_table('entity_relations')
    # ### end Alembic commands ###
