"""phase14: Person, ResourceProfile, ProjectRole, ProjectMembership, Permission, AppRole

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-17 08:48:51.582113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Grundvokabular aus Master-MD Abschnitt 31 - wird per Migration geseedet, kein Auth-System
# im Repo (siehe CONCEPT.md Abschnitt 7), Permissions existieren als Vorbereitung für Phase
# 25/Enterprise-Integration.
_SEED_PERMISSIONS = [
    "PROJECT_CREATE",
    "PROJECT_EDIT",
    "PLANNING_EDIT",
    "CAPACITY_EDIT",
    "TEAM_MANAGE",
    "PERSON_MANAGE",
    "TAG_MANAGE",
    "TAXONOMY_MANAGE",
    "TASK_MANAGE",
    "DECISION_MANAGE",
    "BLOCKER_MANAGE",
    "ADMIN_ACCESS",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resource_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('weekly_hours', sa.Float(), nullable=False),
    sa.Column('capacity_relevant', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['app_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id')
    )
    op.create_table('project_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('project_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_role_id'], ['project_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'person_id')
    )
    # batch_alter_table statt add_column+create_foreign_key direkt: SQLite unterstützt kein
    # ALTER TABLE ... ADD CONSTRAINT (siehe Migration 0002). teams.source/active sind NOT
    # NULL auf einer bereits befüllten Tabelle - server_default nötig, damit bestehende
    # Zeilen einen Wert bekommen (Model-seitiges `default=` ist nur client-seitig und wirkt
    # nicht auf ALTER TABLE ADD COLUMN).
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projektleiter_person_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_projects_projektleiter_person_id_persons', 'persons', ['projektleiter_person_id'], ['id']
        )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_team_members_person_id_persons', 'persons', ['person_id'], ['id'])
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column('source', sa.String(length=30), nullable=False, server_default='LOCAL')
        )
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###

    _seed_permissions()
    _migrate_team_members_to_persons()
    _match_projektleiter_to_persons()


def _seed_permissions() -> None:
    permissions = sa.table("permissions", sa.column("id", sa.Integer), sa.column("name", sa.String))
    bind = op.get_bind()
    for name in _SEED_PERMISSIONS:
        bind.execute(sa.insert(permissions).values(name=name))


def _migrate_team_members_to_persons() -> None:
    """Best-Effort-Mapping (siehe CONCEPT.md Abschnitt 12.3, Frage 4): legt für jedes
    bestehende TeamMember eine Person an und verknüpft sie - additiv, TeamMember bleibt
    bestehen und wird nicht verändert außer um person_id zu setzen."""
    bind = op.get_bind()
    team_members = sa.table(
        "team_members", sa.column("id", sa.Integer), sa.column("name", sa.String), sa.column("person_id", sa.Integer)
    )
    persons = sa.table(
        "persons",
        sa.column("id", sa.Integer),
        sa.column("display_name", sa.String),
        sa.column("source", sa.String),
        sa.column("active", sa.Boolean),
    )
    rows = bind.execute(sa.select(team_members.c.id, team_members.c.name)).fetchall()
    for member_id, name in rows:
        person_id = bind.execute(
            persons.insert().values(display_name=name, source="LOCAL", active=True).returning(persons.c.id)
        ).scalar_one()
        bind.execute(
            sa.update(team_members).where(team_members.c.id == member_id).values(person_id=person_id)
        )


def _match_projektleiter_to_persons() -> None:
    """Best-Effort-Mapping: setzt projects.projektleiter_person_id, wenn der Freitext exakt
    (case-insensitive, getrimmt) genau einer Person entspricht - mehrdeutige oder fehlende
    Treffer bleiben unverändert (projektleiter als Freitext bleibt in jedem Fall die
    verbindliche Anzeige, siehe CONCEPT.md Abschnitt 12.3)."""
    bind = op.get_bind()
    projects = sa.table(
        "projects",
        sa.column("id", sa.Integer),
        sa.column("projektleiter", sa.String),
        sa.column("projektleiter_person_id", sa.Integer),
    )
    persons = sa.table("persons", sa.column("id", sa.Integer), sa.column("display_name", sa.String))

    person_rows = bind.execute(sa.select(persons.c.id, persons.c.display_name)).fetchall()
    by_name: dict[str, list[int]] = {}
    for person_id, display_name in person_rows:
        by_name.setdefault(display_name.strip().lower(), []).append(person_id)

    project_rows = bind.execute(
        sa.select(projects.c.id, projects.c.projektleiter).where(projects.c.projektleiter.isnot(None))
    ).fetchall()
    for project_id, projektleiter in project_rows:
        candidates = by_name.get(projektleiter.strip().lower(), [])
        if len(candidates) == 1:
            bind.execute(
                sa.update(projects).where(projects.c.id == project_id).values(projektleiter_person_id=candidates[0])
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('source')
        batch_op.drop_column('external_id')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_members_person_id_persons', type_='foreignkey')
        batch_op.drop_column('person_id')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_projektleiter_person_id_persons', type_='foreignkey')
        batch_op.drop_column('projektleiter_person_id')
    op.drop_table('project_memberships')
    op.drop_table('role_permissions')
    op.drop_table('resource_profiles')
    op.drop_table('project_roles')
    op.drop_table('persons')
    op.drop_table('permissions')
    op.drop_table('app_roles')
    # ### end Alembic commands ###
