"""phase15: Tag AI-Metadata

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-17 08:58:13.968626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL Boolean-Spalten auf einer bereits befüllten Tabelle brauchen server_default,
    # damit SQLite (und bestehende Postgres-Zeilen) einen Wert für ADD COLUMN haben - Model-
    # seitiges `default=` ist nur client-seitig (siehe Migration 0003).
    op.add_column('tags', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('tags', sa.Column('color', sa.String(length=20), nullable=True))
    op.add_column('tags', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('tags', sa.Column('ai_relevant', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tags', sa.Column('ai_description', sa.String(length=1000), nullable=True))
    op.add_column('tags', sa.Column('synonyms', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'synonyms')
    op.drop_column('tags', 'ai_description')
    op.drop_column('tags', 'ai_relevant')
    op.drop_column('tags', 'active')
    op.drop_column('tags', 'color')
    op.drop_column('tags', 'description')
    # ### end Alembic commands ###
