"""phase16: Blocker, Comment threading, Decision context

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-17 09:08:07.227584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('active_since', sa.String(length=10), nullable=True),
    sa.Column('caused_by_party', sa.String(length=20), nullable=False),
    sa.Column('waiting_for_party', sa.String(length=20), nullable=False),
    sa.Column('owner_person_id', sa.Integer(), nullable=True),
    sa.Column('owner_team_id', sa.Integer(), nullable=True),
    sa.Column('next_action', sa.String(length=500), nullable=True),
    sa.Column('impact', sa.String(length=500), nullable=True),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['owner_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['owner_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # batch_alter_table statt add_column+create_foreign_key direkt: SQLite unterstützt kein
    # ALTER TABLE ... ADD CONSTRAINT (siehe Migration 0002/0003).
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_comments_parent_id_comments', 'comments', ['parent_id'], ['id'])
    op.add_column('decisions', sa.Column('begruendung', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'begruendung')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_parent_id_comments', type_='foreignkey')
        batch_op.drop_column('parent_id')
    op.drop_table('blockers')
    # ### end Alembic commands ###
