"""phase17: PlanPhase, Milestone

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-17 09:17:51.333753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('baseline_date', sa.String(length=10), nullable=True),
    sa.Column('forecast_date', sa.String(length=10), nullable=True),
    sa.Column('actual_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_person_id', sa.Integer(), nullable=True),
    sa.Column('owner_team_id', sa.Integer(), nullable=True),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['owner_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['owner_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=True),
    sa.Column('phase_type', sa.String(length=100), nullable=False),
    sa.Column('baseline_start', sa.String(length=10), nullable=True),
    sa.Column('baseline_end', sa.String(length=10), nullable=True),
    sa.Column('forecast_start', sa.String(length=10), nullable=True),
    sa.Column('forecast_end', sa.String(length=10), nullable=True),
    sa.Column('actual_start', sa.String(length=10), nullable=True),
    sa.Column('actual_end', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('owner_person_id', sa.Integer(), nullable=True),
    sa.Column('owner_team_id', sa.Integer(), nullable=True),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['owner_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['owner_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_phases')
    op.drop_table('milestones')
    # ### end Alembic commands ###
