"""phase19: Capacity Planning Core

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-17 09:53:25.720254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('person_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'skill_id')
    )
    op.create_table('resource_demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('plan_phase_id', sa.Integer(), nullable=True),
    sa.Column('resource_role_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('fte', sa.Float(), nullable=False),
    sa.Column('commitment_level', sa.String(length=20), nullable=False),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['plan_phase_id'], ['plan_phases.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resource_role_id'], ['resource_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_demand_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('fte', sa.Float(), nullable=False),
    sa.Column('erstellt_am', sa.String(length=40), nullable=False),
    sa.Column('aktualisiert_am', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['resource_demand_id'], ['resource_demands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_demand_id', 'person_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_assignments')
    op.drop_table('resource_demands')
    op.drop_table('person_skills')
    op.drop_table('skills')
    op.drop_table('resource_roles')
    # ### end Alembic commands ###
