"""phase22: Project Control & Health

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-17 10:24:43.364357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Default-Schwellwerte (yellow, red) - siehe backend/app/health_calc.py DEFAULT_THRESHOLDS,
# dort auch als defensiver Fallback verwendet, falls eine Zeile fehlt.
_DEFAULT_THRESHOLDS = [
    ("schedule_days", 7, 14),
    ("capacity_fte", 0.2, 0.5),
    ("progress_pp", 10, 20),
    ("risk_score", 3, 5),
    ("blocker_severity", 1, 3),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=30), nullable=False),
    sa.Column('yellow', sa.Float(), nullable=False),
    sa.Column('red', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric')
    )
    # ### end Alembic commands ###

    health_thresholds = sa.table(
        "health_thresholds",
        sa.column("metric", sa.String),
        sa.column("yellow", sa.Float),
        sa.column("red", sa.Float),
    )
    op.bulk_insert(
        health_thresholds,
        [{"metric": metric, "yellow": yellow, "red": red} for metric, yellow, red in _DEFAULT_THRESHOLDS],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_thresholds')
    # ### end Alembic commands ###
