import { useCallback, useEffect, useState } from "react";
import type { FormEvent } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import type { AdminAppRole, AdminCapacityCalendar, AdminHealthThreshold, AdminPermission, AdminPerson, AdminProjectRole, AdminResourceRole, AdminSkill, AdminTag, AdminTagCategory, AiReadinessReport } from "../types";

type Section = "people" | "roles" | "capacity" | "taxonomy" | "health" | "configuration" | "readiness";
const sections: { id: Section; label: string }[] = [
  { id: "people", label: "Personen & Teams" }, { id: "roles", label: "Rollen & Permissions" },
  { id: "capacity", label: "Ressourcen & Skills" }, { id: "taxonomy", label: "Tags & Taxonomie" },
  { id: "health", label: "Project Health" }, { id: "configuration", label: "Konfiguration & Integrationen" },
  { id: "readiness", label: "KI-Readiness" },
];

function NewItemForm({ fields, onSubmit, submitLabel = "Anlegen" }: { fields: { name: string; label: string }[]; onSubmit: (values: Record<string, string>) => Promise<void>; submitLabel?: string }) {
  const [values, setValues] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); try { await onSubmit(values); setValues({}); } finally { setBusy(false); } }
  return <form className="admin-inline-form" onSubmit={submit}>{fields.map(field => <label key={field.name}>{field.label}<input required={field.name === "name" || field.name === "display_name"} value={values[field.name] ?? ""} onChange={event => setValues(current => ({ ...current, [field.name]: event.target.value }))} /></label>)}<button disabled={busy}>{busy ? "Speichert …" : submitLabel}</button></form>;
}

function StatusToggle({ active, onChange, disabled = false }: { active: boolean; onChange: (active: boolean) => void; disabled?: boolean }) {
  return <label className="admin-switch"><input type="checkbox" checked={active} disabled={disabled} onChange={event => onChange(event.target.checked)} /><span>{active ? "Aktiv" : "Inaktiv"}</span></label>;
}

export default function Administration() {
  const [section, setSection] = useState<Section>("people");
  const [people, setPeople] = useState<AdminPerson[]>([]); const [projectRoles, setProjectRoles] = useState<AdminProjectRole[]>([]);
  const [permissions, setPermissions] = useState<AdminPermission[]>([]); const [appRoles, setAppRoles] = useState<AdminAppRole[]>([]);
  const [resourceRoles, setResourceRoles] = useState<AdminResourceRole[]>([]); const [skills, setSkills] = useState<AdminSkill[]>([]);
  const [tags, setTags] = useState<AdminTag[]>([]); const [categories, setCategories] = useState<AdminTagCategory[]>([]);
  const [thresholds, setThresholds] = useState<AdminHealthThreshold[]>([]); const [calendars, setCalendars] = useState<AdminCapacityCalendar[]>([]);
  const [jira, setJira] = useState<{ configured: boolean; tempo_configured?: boolean } | null>(null); const [error, setError] = useState<string | null>(null);
  const [readiness, setReadiness] = useState<AiReadinessReport | null>(null);

  const load = useCallback(async () => { try { setError(null); const result = await Promise.all([api.listPeople(), api.listProjectRoles(), api.listPermissions(), api.listAppRoles(), api.listResourceRoles(), api.listSkills(), api.listAdminTags(), api.listTagCategories(), api.listHealthThresholds(), api.listCapacityCalendars(), api.jiraAdminStatus()]); setPeople(result[0]); setProjectRoles(result[1]); setPermissions(result[2]); setAppRoles(result[3]); setResourceRoles(result[4]); setSkills(result[5]); setTags(result[6]); setCategories(result[7]); setThresholds(result[8]); setCalendars(result[9]); setJira(result[10]); } catch (reason) { setError(reason instanceof Error ? reason.message : "Administration konnte nicht geladen werden"); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (section === "readiness") void api.getAiReadiness().then(setReadiness).catch(reason => setError(reason instanceof Error ? reason.message : "KI-Readiness konnte nicht geladen werden")); }, [section]);
  const perform = async (action: () => Promise<unknown>) => { try { setError(null); await action(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Änderung fehlgeschlagen"); } };

  return <div className="admin-page"><header className="page-header"><div><p className="eyebrow">Systemverwaltung</p><h2>Administration</h2><p>Fachliche Stammdaten, Steuerungsregeln und Integrationen zentral verwalten.</p></div><span className="admin-phase-badge">Phase 25</span></header>
    {error && <div className="admin-alert" role="alert">{error}</div>}
    <nav className="admin-section-nav" aria-label="Administrationsbereiche">{sections.map(item => <button className={section === item.id ? "active" : ""} key={item.id} onClick={() => setSection(item.id)}>{item.label}</button>)}</nav>

    {section === "people" && <div className="admin-grid"><section className="card admin-card admin-card--wide"><h3>Personen</h3><p className="admin-help">Enterprise-synchronisierte Einträge sind gekennzeichnet und können hier nicht deaktiviert werden.</p><NewItemForm fields={[{ name: "display_name", label: "Anzeigename" }, { name: "email", label: "E-Mail" }]} onSubmit={values => perform(() => api.createPerson({ display_name: values.display_name, email: values.email || null }))} />
      <div className="admin-list">{people.map(person => <div className="admin-row" key={person.id}><div><strong>{person.display_name}</strong><small>{person.email || "Keine E-Mail"} · {person.source === "LOCAL" ? "Lokal" : "Enterprise Platform"}</small></div><StatusToggle active={person.active} disabled={person.source !== "LOCAL"} onChange={active => void perform(() => api.updatePerson(person.id, { active }))} /></div>)}</div></section>
      <section className="card admin-card"><h3>Teams</h3><p>Teams und bestehende Kapazitätsressourcen werden in der gemeinsamen Team-Sicht gepflegt.</p><Link className="button-link" to="/team">Teamverwaltung öffnen</Link></section></div>}

    {section === "roles" && <div className="admin-grid"><section className="card admin-card"><h3>Projektrollen</h3><NewItemForm fields={[{ name: "name", label: "Name" }, { name: "description", label: "Beschreibung" }]} onSubmit={values => perform(() => api.createProjectRole({ name: values.name, description: values.description }))} /><div className="admin-list">{projectRoles.map(role => <div className="admin-row" key={role.id}><div><strong>{role.name}</strong><small>{role.description || "Ohne Beschreibung"}</small></div><StatusToggle active={role.active} onChange={active => void perform(() => api.updateProjectRole(role.id, { active }))} /></div>)}</div></section>
      <section className="card admin-card"><h3>App-Rollen & Permissions</h3><NewItemForm fields={[{ name: "name", label: "Rollenname" }, { name: "description", label: "Beschreibung" }]} onSubmit={values => perform(() => api.createAppRole({ name: values.name, description: values.description }))} /><div className="admin-role-matrix">{appRoles.map(role => <details key={role.id}><summary><strong>{role.name}</strong><span>{role.permissions.length} Permissions</span></summary><div className="admin-permissions">{permissions.map(permission => <label key={permission.id} title={permission.description || ""}><input type="checkbox" checked={role.permissions.includes(permission.name)} onChange={event => void perform(() => api.setRolePermission(role.id, permission.id, event.target.checked))} />{permission.name}</label>)}</div></details>)}</div></section></div>}

    {section === "capacity" && <div className="admin-grid"><section className="card admin-card"><h3>Resource Roles</h3><NewItemForm fields={[{ name: "name", label: "Name" }, { name: "description", label: "Beschreibung" }]} onSubmit={values => perform(() => api.createResourceRole({ name: values.name, description: values.description }))} /><div className="admin-list">{resourceRoles.map(role => <div className="admin-row" key={role.id}><div><strong>{role.name}</strong><small>{role.description || "Ohne Beschreibung"}</small></div><StatusToggle active={role.active} onChange={active => void perform(() => api.updateResourceRole(role.id, { active }))} /></div>)}</div></section>
      <section className="card admin-card"><h3>Skills</h3><NewItemForm fields={[{ name: "name", label: "Name" }, { name: "category", label: "Kategorie" }]} onSubmit={values => perform(() => api.createSkill({ name: values.name, category: values.category }))} /><div className="admin-list">{skills.map(skill => <div className="admin-row" key={skill.id}><div><strong>{skill.name}</strong><small>{skill.category || "Ohne Kategorie"}</small></div><StatusToggle active={skill.active} onChange={active => void perform(() => api.updateSkill(skill.id, { active }))} /></div>)}</div></section></div>}

    {section === "taxonomy" && <div className="admin-grid"><section className="card admin-card"><h3>Tag-Kategorien</h3><NewItemForm fields={[{ name: "name", label: "Name" }, { name: "description", label: "Beschreibung" }]} onSubmit={values => perform(() => api.createTagCategory({ name: values.name, description: values.description }))} /><div className="admin-list">{categories.map(category => <div className="admin-row" key={category.id}><div><strong>{category.name}</strong><small>{category.description || "Ohne Beschreibung"}</small></div><span className="admin-count">{tags.filter(tag => tag.category_id === category.id).length} Tags</span></div>)}</div></section>
      <section className="card admin-card"><h3>Tags</h3><NewItemForm fields={[{ name: "name", label: "Tag-Name" }]} onSubmit={values => perform(() => api.createAdminTag({ name: values.name }))} /><div className="admin-list">{tags.map(tag => <div className="admin-row" key={tag.id}><div><strong>#{tag.name}</strong><select aria-label={`Kategorie für ${tag.name}`} value={tag.category_id ?? ""} onChange={event => void perform(() => api.updateAdminTag(tag.id, { category_id: event.target.value ? Number(event.target.value) : null }))}><option value="">Ohne Kategorie</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div><StatusToggle active={tag.active} onChange={active => void perform(() => api.updateAdminTag(tag.id, { active }))} /></div>)}</div></section></div>}

    {section === "health" && <section className="card admin-card admin-card--wide"><h3>Project-Health-Schwellwerte</h3><p className="admin-help">Gelb und Rot bezeichnen den jeweiligen Badness-Wert, ab dem der Status wechselt.</p><div className="admin-threshold-grid">{thresholds.map(item => <ThresholdEditor key={item.metric} value={item} save={(yellow, red) => perform(() => api.updateHealthThreshold(item.metric, { yellow, red }))} />)}</div></section>}

    {section === "configuration" && <div className="admin-grid"><section className="card admin-card"><h3>Capacity-Konfiguration</h3><NewItemForm fields={[{ name: "name", label: "Kalendername" }, { name: "description", label: "Beschreibung" }]} onSubmit={values => perform(() => api.createCapacityCalendar({ name: values.name, description: values.description }))} /><div className="admin-list">{calendars.map(calendar => <div className="admin-row" key={calendar.id}><div><strong>{calendar.name}</strong><small>{calendar.description || "Ohne Beschreibung"}</small></div><StatusToggle active={calendar.active} onChange={active => void perform(() => api.updateCapacityCalendar(calendar.id, { active }))} /></div>)}</div></section>
      <section className="card admin-card"><h3>Integrationen</h3><div className="integration-tile"><div><strong>Jira Cloud</strong><small>Actual Effort und Projektmetadaten</small></div><span className={jira?.configured ? "status-ok" : "status-off"}>{jira?.configured ? "Verbunden" : "Nicht konfiguriert"}</span></div><div className="integration-tile"><div><strong>Tempo Timesheets</strong><small>Optionale Worklog-Quelle</small></div><span className={jira?.tempo_configured ? "status-ok" : "status-off"}>{jira?.tempo_configured ? "Verbunden" : "Optional"}</span></div><p className="admin-help">Zugangsdaten werden sicher über Umgebungsvariablen bereitgestellt und nicht in der UI gespeichert.</p><Link className="button-link" to="/jira-projekte">Jira-Projekte öffnen</Link></section>
      <section className="card admin-card"><h3>Blocker- & Risiko-Konfiguration</h3><p>Severity und Risikolevel verwenden aktuell das etablierte Fachvokabular der Activity-Objekte. Eigene Kategorien benötigen vor einer UI einen expliziten Domänenentscheid.</p><span className="admin-readonly">Aktuell systemverwaltet</span></section></div>}

    {section === "readiness" && <section className="card admin-card admin-card--wide"><div className="readiness-header"><div><h3>KI-Readiness Review</h3><p className="admin-help">Read-only Architektur- und Datenqualitätsprüfung. Es wird kein KI-Agent aktiviert.</p></div>{readiness && <span className={`readiness-status readiness-status--${readiness.overall_status.toLowerCase()}`}>{readiness.overall_status}</span>}</div>
      {!readiness ? <p>Review wird geladen …</p> : <><div className="readiness-summary"><strong>{readiness.checks.filter(check => check.status === "READY").length}/{readiness.checks.length}</strong><span>Prüfpunkte bereit</span><small>Stand {new Date(readiness.generated_at).toLocaleString("de-DE")}</small></div><div className="readiness-list">{readiness.checks.map(check => <article key={check.key} className="readiness-check"><span className={`readiness-dot readiness-dot--${check.status.toLowerCase()}`} aria-label={check.status} /><div><strong>{check.label}</strong><p>{check.evidence}</p>{check.metrics.length > 0 && <div className="readiness-metrics">{check.metrics.map(metric => <span key={metric.key}>{metric.value}{metric.unit ? ` ${metric.unit}` : ""}</span>)}</div>}{check.recommendation && <small>Nächster Schritt: {check.recommendation}</small>}</div></article>)}</div>{readiness.blockers.length > 0 && <div className="readiness-blocker"><strong>Freigabe für produktiven Agenten gesperrt</strong><p>{readiness.blockers.join(" ")}</p></div>}</>}
    </section>}
  </div>;
}

function ThresholdEditor({ value, save }: { value: AdminHealthThreshold; save: (yellow: number, red: number) => Promise<void> }) {
  const [yellow, setYellow] = useState(value.yellow); const [red, setRed] = useState(value.red);
  useEffect(() => { setYellow(value.yellow); setRed(value.red); }, [value]);
  return <form onSubmit={event => { event.preventDefault(); void save(yellow, red); }}><strong>{value.metric}</strong><label>Gelb<input type="number" step="0.1" min="0" value={yellow} onChange={event => setYellow(Number(event.target.value))} /></label><label>Rot<input type="number" step="0.1" min={yellow} value={red} onChange={event => setRed(Number(event.target.value))} /></label><button>Speichern</button></form>;
}
